Fix odd even
Em-AK/openfoodnetwork pull request #16
Opened 2017-08-09 12:34 UTC by sauloperez

#### What? Why?

[Explain why is this change needed and the solution you propose. Provide
context for others to understand it]

#### What should we test?

[List which features should be tested and how]

#### Release notes

[In case this should be present in the release notes, please write them or
remove this section otherwise]

#### How is this related to the Spree upgrade?

[Any known conflicts with the Spree Upgrade? explain them or remove this section
otherwise]

#### Discourse thread

[Is there a discussion about this in Discourse? add the link if so or remove
this section otherwise]

#### Dependencies

[Does this PR depend on another one? add the link of so or remove this section
otherwise]

2017-08-09 16:58 UTC, sauloperez commented on Gemfile
> +gem 'spree', github: 'coopdevs/spree', branch: 'fix-odd-even'
update me when that branch gets merged into `spree-upgrade-step-6`.

2017-08-10 12:01 UTC, sauloperez commented on spec/controllers/admin/bulk_line_items_controller_spec.rb
> +            expect_any_instance_of(Spree::Order).to receive(:update_distribution_charge!)
I can't understand why but I can't make it pass with `expect(order1).to ...` although the instance is indeed the same that receives the method calls.

2017-08-11 13:44 UTC, enricostano requested changes

2017-08-11 13:44 UTC, enricostano commented on spec/controllers/admin/bulk_line_items_controller_spec.rb
> +            expect_any_instance_of(Spree::Order).to receive(:update_distribution_charge!)
I don't like this 😭

2017-08-11 14:47 UTC, enricostano commented on spec/controllers/admin/bulk_line_items_controller_spec.rb
> +            expect_any_instance_of(Spree::Order).to receive(:update_distribution_charge!)
Opened an issue to fix this https://github.com/openfoodfoundation/openfoodnetwork/issues/1762

2017-08-11 14:47 UTC, enricostano approved these changes

2017-08-11 14:48 UTC, merged